### ISSUE TITLE
Colocar a tag de compatibilidade com o IE em todas as páginas

### ISSUE THREAD

**Issue by fabriciofx** [fellipealvess/DSWI#1]
@fellipealvess Adicionar a tag de compatibilidade com o IE em todas as páginas:

`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by fellipealvess** [comment]
adicionado, creio que no local adequado

**Comment by fabriciofx** [comment]
@fellipealvess Ok!
